[project]
name = "shade-agent-client"
version = "0.1.0"
description = "A Shade Agent for NEAR"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dstack-sdk>=0.1.8",
    "near-omni-client>=0.0.1",
]
